import os
from crewai import Agent, Task, Crew, Process, LLM
from dotenv import load_dotenv

load_dotenv()

# --- 1. CONFIGURE OPENROUTER FREE-TIER VIA CREWAI LLM WRAPPER ---
# CrewAI uses an explicit LLM object wrapper to handle third-party endpoints.
custom_llm = LLM(
    model="openrouter/openrouter/free",
    base_url="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENROUTER_API_KEY"),
    temperature=0.3
)

print("🚀 Initializing Specialist Agents for DevMind Documentation Team...")

# --- 2. DEFINE AGENTS (ROLES, GOALS, & BACKSTORY) ---

researcher = Agent(
    role="Principal Technical Researcher",
    goal="Uncover cutting-edge facts and foundational concepts regarding {topic}.",
    backstory="You are an elite research analyst specializing in breaking down dense, complex technological paradigms into clear, verified data structures.",
    verbose=True,
    llm=custom_llm
)

writer = Agent(
    role="Senior Technical Writer",
    goal="Transform technical research findings into an engaging, clear, and well-structured blog post.",
    backstory="You are a veteran developer-advocate who translates raw data tables and technical concepts into compelling prose that software engineers love to read.",
    verbose=True,
    llm=custom_llm
)

editor = Agent(
    role="Chief Editorial Director",
    goal="Review technical content drafts for accuracy, clarity, tone, and professional polish.",
    backstory="You are a meticulous editor. You ensure that all technical write-ups are accurate, clear of fluff, properly formatted, and direct.",
    verbose=True,
    llm=custom_llm
)

# --- 3. DEFINE THE TASKS (ASSIGNED TO SPECIFIC AGENTS) ---

research_task = Task(
    description=(
        "Conduct detailed research on the following topic: '{topic}'. "
        "Identify the top 3 core engineering breakthroughs, use-cases, and their long-term industry significance."
    ),
    expected_output="A structured bulleted list outlining 3 core breakthroughs with accompanying technical details.",
    agent=researcher
)

write_task = Task(
    description=(
        "Review the structured data points provided by the Principal Technical Researcher. "
        "Compose a cohesive, comprehensive technical blog post based on those insights. "
        "The post must include an introduction, deep-dive sections for each breakthrough, and a forward-looking conclusion."
    ),
    expected_output="A full technical blog post draft ready for review.",
    agent=writer
)

edit_task = Task(
    description=(
        "Audit the technical blog post draft generated by the Senior Technical Writer. "
        "Refine formatting, eliminate passive phrasing, ensure accurate technical positioning, and check alignment with the original research data."
    ),
    expected_output="A polished, production-ready technical blog post text block.",
    agent=editor,
    output_file="devmind_blog_post.md"
)

# --- 4. ASSEMBLE THE CREW AS A SEQUENTIAL ASSEMBLY LINE ---

devmind_doc_crew = Crew(
    agents=[researcher, writer, editor],
    tasks=[research_task, write_task, edit_task],
    process=Process.sequential,  # Linear dependency execution chain
    verbose=True
)

# --- 5. KICK OFF THE SYSTEM LIFE CYCLE ---
if __name__ == "__main__":
    target_topic = "LangGraph vs CrewAI orchestration choices for multi-agent architecture in 2026"
    
    print(f"\n🎬 Activating Crew pipeline to analyze: '{target_topic}'...\n")
    
    # Ingest inputs directly into the parameterized task string brackets
    result = devmind_doc_crew.kickoff(inputs={"topic": target_topic})
    
    print("\n" + "="*60)
    print("🎯 FINAL PRODUCTION-READY OUTPUT:")
    print("="*60 + "\n")
    print(result)